# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.metric_api import MetricApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestMetricApi(unittest.TestCase):
    """MetricApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.metric_api.MetricApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_with_predicate2(self):
        """Test case for count_with_predicate2

        """
        pass

    def test_create_multiple2(self):
        """Test case for create_multiple2

        """
        pass

    def test_delete2(self):
        """Test case for delete2

        """
        pass

    def test_delete_all2(self):
        """Test case for delete_all2

        """
        pass

    def test_edit_multiple2(self):
        """Test case for edit_multiple2

        """
        pass

    def test_get5(self):
        """Test case for get5

        """
        pass

    def test_get6(self):
        """Test case for get6

        """
        pass

    def test_get_all2(self):
        """Test case for get_all2

        """
        pass


if __name__ == '__main__':
    unittest.main()
