# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.task_api import TaskApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.task_api.TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_with_predicate10(self):
        """Test case for count_with_predicate10

        """
        pass

    def test_delete10(self):
        """Test case for delete10

        """
        pass

    def test_delete_all10(self):
        """Test case for delete_all10

        """
        pass

    def test_get21(self):
        """Test case for get21

        """
        pass

    def test_get22(self):
        """Test case for get22

        """
        pass

    def test_get_all10(self):
        """Test case for get_all10

        """
        pass

    def test_purge(self):
        """Test case for purge

        """
        pass


if __name__ == '__main__':
    unittest.main()
