# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.subscription_group_api import SubscriptionGroupApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestSubscriptionGroupApi(unittest.TestCase):
    """SubscriptionGroupApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.subscription_group_api.SubscriptionGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_with_predicate6(self):
        """Test case for count_with_predicate6

        """
        pass

    def test_create_multiple6(self):
        """Test case for create_multiple6

        """
        pass

    def test_delete6(self):
        """Test case for delete6

        """
        pass

    def test_delete_all6(self):
        """Test case for delete_all6

        """
        pass

    def test_edit_multiple6(self):
        """Test case for edit_multiple6

        """
        pass

    def test_get13(self):
        """Test case for get13

        """
        pass

    def test_get14(self):
        """Test case for get14

        """
        pass

    def test_get_all6(self):
        """Test case for get_all6

        """
        pass

    def test_reset1(self):
        """Test case for reset1

        """
        pass


if __name__ == '__main__':
    unittest.main()
