# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.ui_configuration_api import UIConfigurationApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestUIConfigurationApi(unittest.TestCase):
    """UIConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.ui_configuration_api.UIConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get23(self):
        """Test case for get23

        """
        pass


if __name__ == '__main__':
    unittest.main()
