# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.event_api import EventApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.event_api.EventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_with_predicate9(self):
        """Test case for count_with_predicate9

        """
        pass

    def test_create_multiple9(self):
        """Test case for create_multiple9

        """
        pass

    def test_delete9(self):
        """Test case for delete9

        """
        pass

    def test_delete_all9(self):
        """Test case for delete_all9

        """
        pass

    def test_edit_multiple9(self):
        """Test case for edit_multiple9

        """
        pass

    def test_get19(self):
        """Test case for get19

        """
        pass

    def test_get20(self):
        """Test case for get20

        """
        pass

    def test_get_all9(self):
        """Test case for get_all9

        """
        pass

    def test_load_holidays(self):
        """Test case for load_holidays

        """
        pass

    def test_load_holidays1(self):
        """Test case for load_holidays1

        """
        pass


if __name__ == '__main__':
    unittest.main()
