# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.entity_api import EntityApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestEntityApi(unittest.TestCase):
    """EntityApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.entity_api.EntityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_entity(self):
        """Test case for get_entity

        """
        pass

    def test_get_entity_info(self):
        """Test case for get_entity_info

        """
        pass

    def test_get_raw_entity(self):
        """Test case for get_raw_entity

        """
        pass

    def test_list_entities(self):
        """Test case for list_entities

        """
        pass


if __name__ == '__main__':
    unittest.main()
