# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.models.templatable_object import TemplatableObject  # noqa: E501
from thirdeye_client.rest import ApiException


class TestTemplatableObject(unittest.TestCase):
    """TemplatableObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplatableObject(self):
        """Test TemplatableObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thirdeye_client.models.templatable_object.TemplatableObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
