# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.alert_template_api import AlertTemplateApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestAlertTemplateApi(unittest.TestCase):
    """AlertTemplateApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.alert_template_api.AlertTemplateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_with_predicate4(self):
        """Test case for count_with_predicate4

        """
        pass

    def test_create_multiple4(self):
        """Test case for create_multiple4

        """
        pass

    def test_delete4(self):
        """Test case for delete4

        """
        pass

    def test_delete_all4(self):
        """Test case for delete_all4

        """
        pass

    def test_edit_multiple4(self):
        """Test case for edit_multiple4

        """
        pass

    def test_get10(self):
        """Test case for get10

        """
        pass

    def test_get9(self):
        """Test case for get9

        """
        pass

    def test_get_all4(self):
        """Test case for get_all4

        """
        pass

    def test_load_recommended_templates(self):
        """Test case for load_recommended_templates

        """
        pass


if __name__ == '__main__':
    unittest.main()
