# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thirdeye_client
from thirdeye_client.api.auth_info_api import AuthInfoApi  # noqa: E501
from thirdeye_client.rest import ApiException


class TestAuthInfoApi(unittest.TestCase):
    """AuthInfoApi unit test stubs"""

    def setUp(self):
        self.api = thirdeye_client.api.auth_info_api.AuthInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get(self):
        """Test case for get

        """
        pass


if __name__ == '__main__':
    unittest.main()
