# coding: utf-8

# flake8: noqa

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import ApiClient
from thirdeye_client.api_client import ApiClient
from thirdeye_client.configuration import Configuration