# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thirdeye_client.configuration import Configuration


class AppAnalyticsResourceModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'ResponseModel',
        'analytics_payload': 'ResponseModel'
    }

    attribute_map = {
        'version': 'version',
        'analytics_payload': 'analyticsPayload'
    }

    def __init__(self, version=None, analytics_payload=None, _configuration=None):  # noqa: E501
        """AppAnalyticsResourceModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._version = None
        self._analytics_payload = None
        self.discriminator = None

        if version is not None:
            self.version = version
        if analytics_payload is not None:
            self.analytics_payload = analytics_payload

    @property
    def version(self):
        """Gets the version of this AppAnalyticsResourceModel.  # noqa: E501


        :return: The version of this AppAnalyticsResourceModel.  # noqa: E501
        :rtype: ResponseModel
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this AppAnalyticsResourceModel.


        :param version: The version of this AppAnalyticsResourceModel.  # noqa: E501
        :type: ResponseModel
        """

        self._version = version

    @property
    def analytics_payload(self):
        """Gets the analytics_payload of this AppAnalyticsResourceModel.  # noqa: E501


        :return: The analytics_payload of this AppAnalyticsResourceModel.  # noqa: E501
        :rtype: ResponseModel
        """
        return self._analytics_payload

    @analytics_payload.setter
    def analytics_payload(self, analytics_payload):
        """Sets the analytics_payload of this AppAnalyticsResourceModel.


        :param analytics_payload: The analytics_payload of this AppAnalyticsResourceModel.  # noqa: E501
        :type: ResponseModel
        """

        self._analytics_payload = analytics_payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppAnalyticsResourceModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppAnalyticsResourceModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AppAnalyticsResourceModel):
            return True

        return self.to_dict() != other.to_dict()
