# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thirdeye_client.configuration import Configuration


class EventApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'metric': 'str',
        'service': 'str',
        'type': 'str',
        'start_time': 'int',
        'end_time': 'int',
        'target_dimension_map': 'dict(str, list[str])'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'metric': 'metric',
        'service': 'service',
        'type': 'type',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'target_dimension_map': 'targetDimensionMap'
    }

    def __init__(self, id=None, name=None, metric=None, service=None, type=None, start_time=None, end_time=None, target_dimension_map=None, _configuration=None):  # noqa: E501
        """EventApi - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._metric = None
        self._service = None
        self._type = None
        self._start_time = None
        self._end_time = None
        self._target_dimension_map = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if metric is not None:
            self.metric = metric
        if service is not None:
            self.service = service
        if type is not None:
            self.type = type
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if target_dimension_map is not None:
            self.target_dimension_map = target_dimension_map

    @property
    def id(self):
        """Gets the id of this EventApi.  # noqa: E501


        :return: The id of this EventApi.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EventApi.


        :param id: The id of this EventApi.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this EventApi.  # noqa: E501


        :return: The name of this EventApi.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EventApi.


        :param name: The name of this EventApi.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def metric(self):
        """Gets the metric of this EventApi.  # noqa: E501


        :return: The metric of this EventApi.  # noqa: E501
        :rtype: str
        """
        return self._metric

    @metric.setter
    def metric(self, metric):
        """Sets the metric of this EventApi.


        :param metric: The metric of this EventApi.  # noqa: E501
        :type: str
        """

        self._metric = metric

    @property
    def service(self):
        """Gets the service of this EventApi.  # noqa: E501


        :return: The service of this EventApi.  # noqa: E501
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this EventApi.


        :param service: The service of this EventApi.  # noqa: E501
        :type: str
        """

        self._service = service

    @property
    def type(self):
        """Gets the type of this EventApi.  # noqa: E501


        :return: The type of this EventApi.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this EventApi.


        :param type: The type of this EventApi.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def start_time(self):
        """Gets the start_time of this EventApi.  # noqa: E501


        :return: The start_time of this EventApi.  # noqa: E501
        :rtype: int
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this EventApi.


        :param start_time: The start_time of this EventApi.  # noqa: E501
        :type: int
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this EventApi.  # noqa: E501


        :return: The end_time of this EventApi.  # noqa: E501
        :rtype: int
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this EventApi.


        :param end_time: The end_time of this EventApi.  # noqa: E501
        :type: int
        """

        self._end_time = end_time

    @property
    def target_dimension_map(self):
        """Gets the target_dimension_map of this EventApi.  # noqa: E501


        :return: The target_dimension_map of this EventApi.  # noqa: E501
        :rtype: dict(str, list[str])
        """
        return self._target_dimension_map

    @target_dimension_map.setter
    def target_dimension_map(self, target_dimension_map):
        """Sets the target_dimension_map of this EventApi.


        :param target_dimension_map: The target_dimension_map of this EventApi.  # noqa: E501
        :type: dict(str, list[str])
        """

        self._target_dimension_map = target_dimension_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventApi, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventApi):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EventApi):
            return True

        return self.to_dict() != other.to_dict()
