# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thirdeye_client.configuration import Configuration


class LinkModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'params': 'dict(str, str)',
        'uri': 'str',
        'uri_builder': 'UriBuilderModel',
        'rel': 'str',
        'rels': 'list[str]',
        'type': 'str'
    }

    attribute_map = {
        'title': 'title',
        'params': 'params',
        'uri': 'uri',
        'uri_builder': 'uriBuilder',
        'rel': 'rel',
        'rels': 'rels',
        'type': 'type'
    }

    def __init__(self, title=None, params=None, uri=None, uri_builder=None, rel=None, rels=None, type=None, _configuration=None):  # noqa: E501
        """LinkModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._title = None
        self._params = None
        self._uri = None
        self._uri_builder = None
        self._rel = None
        self._rels = None
        self._type = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if params is not None:
            self.params = params
        if uri is not None:
            self.uri = uri
        if uri_builder is not None:
            self.uri_builder = uri_builder
        if rel is not None:
            self.rel = rel
        if rels is not None:
            self.rels = rels
        if type is not None:
            self.type = type

    @property
    def title(self):
        """Gets the title of this LinkModel.  # noqa: E501


        :return: The title of this LinkModel.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this LinkModel.


        :param title: The title of this LinkModel.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def params(self):
        """Gets the params of this LinkModel.  # noqa: E501


        :return: The params of this LinkModel.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this LinkModel.


        :param params: The params of this LinkModel.  # noqa: E501
        :type: dict(str, str)
        """

        self._params = params

    @property
    def uri(self):
        """Gets the uri of this LinkModel.  # noqa: E501


        :return: The uri of this LinkModel.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this LinkModel.


        :param uri: The uri of this LinkModel.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def uri_builder(self):
        """Gets the uri_builder of this LinkModel.  # noqa: E501


        :return: The uri_builder of this LinkModel.  # noqa: E501
        :rtype: UriBuilderModel
        """
        return self._uri_builder

    @uri_builder.setter
    def uri_builder(self, uri_builder):
        """Sets the uri_builder of this LinkModel.


        :param uri_builder: The uri_builder of this LinkModel.  # noqa: E501
        :type: UriBuilderModel
        """

        self._uri_builder = uri_builder

    @property
    def rel(self):
        """Gets the rel of this LinkModel.  # noqa: E501


        :return: The rel of this LinkModel.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this LinkModel.


        :param rel: The rel of this LinkModel.  # noqa: E501
        :type: str
        """

        self._rel = rel

    @property
    def rels(self):
        """Gets the rels of this LinkModel.  # noqa: E501


        :return: The rels of this LinkModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._rels

    @rels.setter
    def rels(self, rels):
        """Sets the rels of this LinkModel.


        :param rels: The rels of this LinkModel.  # noqa: E501
        :type: list[str]
        """

        self._rels = rels

    @property
    def type(self):
        """Gets the type of this LinkModel.  # noqa: E501


        :return: The type of this LinkModel.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LinkModel.


        :param type: The type of this LinkModel.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LinkModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinkModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LinkModel):
            return True

        return self.to_dict() != other.to_dict()
