# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thirdeye_client.configuration import Configuration


class NotificationSchemesApiModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'EmailSchemeApiModel',
        'webhook': 'WebhookSchemeApiModel'
    }

    attribute_map = {
        'email': 'email',
        'webhook': 'webhook'
    }

    def __init__(self, email=None, webhook=None, _configuration=None):  # noqa: E501
        """NotificationSchemesApiModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._email = None
        self._webhook = None
        self.discriminator = None

        if email is not None:
            self.email = email
        if webhook is not None:
            self.webhook = webhook

    @property
    def email(self):
        """Gets the email of this NotificationSchemesApiModel.  # noqa: E501


        :return: The email of this NotificationSchemesApiModel.  # noqa: E501
        :rtype: EmailSchemeApiModel
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this NotificationSchemesApiModel.


        :param email: The email of this NotificationSchemesApiModel.  # noqa: E501
        :type: EmailSchemeApiModel
        """

        self._email = email

    @property
    def webhook(self):
        """Gets the webhook of this NotificationSchemesApiModel.  # noqa: E501


        :return: The webhook of this NotificationSchemesApiModel.  # noqa: E501
        :rtype: WebhookSchemeApiModel
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook):
        """Sets the webhook of this NotificationSchemesApiModel.


        :param webhook: The webhook of this NotificationSchemesApiModel.  # noqa: E501
        :type: WebhookSchemeApiModel
        """

        self._webhook = webhook

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NotificationSchemesApiModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationSchemesApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NotificationSchemesApiModel):
            return True

        return self.to_dict() != other.to_dict()
