# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thirdeye_client.configuration import Configuration


class PlanNodeApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'params': 'dict(str, TemplatableObject)',
        'inputs': 'list[InputApi]',
        'outputs': 'list[OutputApi]'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'params': 'params',
        'inputs': 'inputs',
        'outputs': 'outputs'
    }

    def __init__(self, name=None, type=None, params=None, inputs=None, outputs=None, _configuration=None):  # noqa: E501
        """PlanNodeApi - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._type = None
        self._params = None
        self._inputs = None
        self._outputs = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if params is not None:
            self.params = params
        if inputs is not None:
            self.inputs = inputs
        if outputs is not None:
            self.outputs = outputs

    @property
    def name(self):
        """Gets the name of this PlanNodeApi.  # noqa: E501


        :return: The name of this PlanNodeApi.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PlanNodeApi.


        :param name: The name of this PlanNodeApi.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this PlanNodeApi.  # noqa: E501


        :return: The type of this PlanNodeApi.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PlanNodeApi.


        :param type: The type of this PlanNodeApi.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def params(self):
        """Gets the params of this PlanNodeApi.  # noqa: E501


        :return: The params of this PlanNodeApi.  # noqa: E501
        :rtype: dict(str, TemplatableObject)
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this PlanNodeApi.


        :param params: The params of this PlanNodeApi.  # noqa: E501
        :type: dict(str, TemplatableObject)
        """

        self._params = params

    @property
    def inputs(self):
        """Gets the inputs of this PlanNodeApi.  # noqa: E501


        :return: The inputs of this PlanNodeApi.  # noqa: E501
        :rtype: list[InputApi]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this PlanNodeApi.


        :param inputs: The inputs of this PlanNodeApi.  # noqa: E501
        :type: list[InputApi]
        """

        self._inputs = inputs

    @property
    def outputs(self):
        """Gets the outputs of this PlanNodeApi.  # noqa: E501


        :return: The outputs of this PlanNodeApi.  # noqa: E501
        :rtype: list[OutputApi]
        """
        return self._outputs

    @outputs.setter
    def outputs(self, outputs):
        """Sets the outputs of this PlanNodeApi.


        :param outputs: The outputs of this PlanNodeApi.  # noqa: E501
        :type: list[OutputApi]
        """

        self._outputs = outputs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanNodeApi, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanNodeApi):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PlanNodeApi):
            return True

        return self.to_dict() != other.to_dict()
