# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thirdeye_client.configuration import Configuration


class TimeColumnApiModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'interval': 'DurationModel',
        'format': 'str',
        'timezone': 'str'
    }

    attribute_map = {
        'name': 'name',
        'interval': 'interval',
        'format': 'format',
        'timezone': 'timezone'
    }

    def __init__(self, name=None, interval=None, format=None, timezone=None, _configuration=None):  # noqa: E501
        """TimeColumnApiModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._interval = None
        self._format = None
        self._timezone = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if interval is not None:
            self.interval = interval
        if format is not None:
            self.format = format
        if timezone is not None:
            self.timezone = timezone

    @property
    def name(self):
        """Gets the name of this TimeColumnApiModel.  # noqa: E501


        :return: The name of this TimeColumnApiModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TimeColumnApiModel.


        :param name: The name of this TimeColumnApiModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def interval(self):
        """Gets the interval of this TimeColumnApiModel.  # noqa: E501


        :return: The interval of this TimeColumnApiModel.  # noqa: E501
        :rtype: DurationModel
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this TimeColumnApiModel.


        :param interval: The interval of this TimeColumnApiModel.  # noqa: E501
        :type: DurationModel
        """

        self._interval = interval

    @property
    def format(self):
        """Gets the format of this TimeColumnApiModel.  # noqa: E501


        :return: The format of this TimeColumnApiModel.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this TimeColumnApiModel.


        :param format: The format of this TimeColumnApiModel.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def timezone(self):
        """Gets the timezone of this TimeColumnApiModel.  # noqa: E501


        :return: The timezone of this TimeColumnApiModel.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this TimeColumnApiModel.


        :param timezone: The timezone of this TimeColumnApiModel.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeColumnApiModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeColumnApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TimeColumnApiModel):
            return True

        return self.to_dict() != other.to_dict()
